[package]
name = "faf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
clap = { version = "4.2.7", features = ["derive"] }
home = "0.5.5"
joatmon = "0.0.20"
md5 = "0.7.0"
path-absolutize = "3.1.0"
serde = { version = "1.0.162", features = ["derive"] }
serde_yaml = "0.9.21"
uuid = { version = "1.3.2", features = ["v4", "serde"] }
